version: "2.12"
services:
  # Container that runs HDFS NameNode and DataNode services
  hdfs-namenode:
    image: hdfs-namenode
    hostname: hdfs-namenode-host
    ports:
      # HDFS port
      - "9000:9000"
      # HDFS NameNode WebUI
      - "9870:9870"
    # Adjust according to the resources available on host machine
    cpu_shares: 3000
    mem_limit: 2g
    stdin_open: true
    tty: true

  # Container that runs HDFS DataNode service
  hdfs-datanode:
    image: hdfs-datanode
    hostname: hdfs-datanode-host
    links:
      - hdfs-namenode
    environment:
      # NAMENODE_HOSTNAME is the hostname of the container running Namenode service
      - NAMENODE_HOSTNAME=hdfs-namenode-host
    # Adjust according to the resources available on host machine
    cpu_shares: 3000
    mem_limit: 2g